### ISSUE TITLE
Data needed to reproduce the module merging code

### ISSUE THREAD

**Issue by ShaolongCao** [dhglab/multiregional-networks#1]
Hi there,

I am trying to apply the module merging steps in this code: https://github.com/dhglab/multiregional-networks/tree/master/network_construction/hierarchical_merging)/02_merge_modules_FINAL.R

However, I couldn't find the following data to reproduce the code. 
load('./module_eigengenes.withlandmarks.Rda')
module.defs <- read.table('module.table.txt', header=T, row.names=1)
module.color.defs <- read.table('module.color.table.txt', header=T, row.names=1)

Could you please share the data so that I can reproduce it?

Thanks,
Shaolong

**Comment by chartl** [comment]
This file is produced by 01_gene_cluster_hierarchy.R and access to the GTEx data is required to run that. This component of the repository exists to document how the data was produced, i.e., the steps taken to generate the final analysis modules; but it was not intended as a push-button mechanism for re-generating the modules from the raw data (as any changes to underlying tools or packages may impact the results). Please see the code criticality statement for more details.
